PR User Reviews
MinoUni/Marketplace-Bookti pull request #3
Opened 2024-05-22 17:14 UTC by Lyubomy-r

- in the User class, the added fields rating and fields receivedReviews, leftReviews to bidirectional connection.
- the rating field has been added in the User ProfileDTO class
- u.rating was added in the UserRepository class, in the Query method findUserFullInfoById()
- in the UserControllerTest class, the rating value was added in the shouldReturnMailResetPasswordResponseWithStatusCode200 test

-classes have been created ReviewController, UserReview, UserReviewDTO, UserReviewRepository, UserReviewResponseDTO, UserReviewSaveDTO, UserReviewService, UserReviewServiceImp 
-created tests ReviewControllerTest, UserReviewRepositoryTest, UserReviewServiceImpTest,

-INSERT INTO user_review was added in the data.sql file and rating was added to the previous INSERT into users

2024-05-25 13:20 UTC, MinoUni requested changes
1. Install google-java-formatter plugin and format code;
2. Refactor namings corresponding to requested changes(request paths, tests namings, etc);

2024-05-25 13:20 UTC, MinoUni commented on pom.xml
> +<!--        </dependency>-->
Use non-in-memory db in runtime

2024-05-25 13:20 UTC, MinoUni commented on pom.xml
> +            <scope>runtime</scope>
Return test scope

2024-05-25 13:20 UTC, MinoUni commented on src/main/java/com/teamchallenge/bookti/review/ReviewController.java
> +    }
Path userId with ReqParam
expl: /reviews?userId=<value> || /reviews?[ filter ] || in payload

2024-05-25 13:20 UTC, MinoUni commented on src/main/java/com/teamchallenge/bookti/review/ReviewController.java
> +    @PostMapping("/user")
```suggestion
    @PostMapping
```
You work with review resources, add user data if it needed to payload or reqParam

2024-05-25 13:20 UTC, MinoUni commented on src/main/java/com/teamchallenge/bookti/review/ReviewController.java
> +    @DeleteMapping("/user/{reviewId}")
```suggestion
    @DeleteMapping("/{reviewId}")
```
As previous

2024-05-25 13:20 UTC, MinoUni commented on src/main/java/com/teamchallenge/bookti/review/UserReviewDTO.java
> +    }
Replace with mapstruct mapper

2024-05-25 13:20 UTC, MinoUni commented on src/main/java/com/teamchallenge/bookti/review/UserReviewServiceImp.java
> +    }
```suggestion
    @Override
    public List<UserReview> findAllUserReceivedReviewsById(Integer userId) {
      if (!userRepository.existsById(userId)) {
        log.info("message");
        throw new UserNotFoundException(String.format(UserConstant.NOT_FOUND_MESSAGE, userId));        
      }
      List<UserReview> userReviewList = userReviewRepository.findAllUserReceivedReviewsById(userId);
      log.info("From UserReviewServiceImp method - findAllUserReviewById - return list or empty list, received review to user: {}.", userId);
      return userReviewList;
    }
```
If you need only check the existence of the model without reading the data -> use existsBy();
If you need to read model data and verify that the model is present -> use findBy();

2024-05-25 13:20 UTC, MinoUni commented on src/main/java/com/teamchallenge/bookti/review/UserReviewServiceImp.java
> +        }
same as previous

2024-05-25 13:20 UTC, MinoUni commented on src/main/java/com/teamchallenge/bookti/review/UserReviewServiceImp.java
> +    }
replace with mapper using mapstruct

2024-05-25 13:20 UTC, MinoUni commented on src/main/java/com/teamchallenge/bookti/review/UserReviewServiceImp.java
> +        if (checkValidUserId(reviewerId, review.getOwnerId())) {
```suggestion
        if (Objects.equals(reviewerId, review.getOwnerId())) {
```
Or remove a review owner from DTO and extract owner id from access token

2024-05-25 13:20 UTC, MinoUni commented on src/main/java/com/teamchallenge/bookti/review/UserReviewServiceImp.java
> +                        () -> new UserNotFoundException(format("Reviewer's User with id <{0}> not found.", reviewId)));
Replace with `existsById(reviewId)` method, it doesn't need to use resources to read data from db and then delete it.

2024-05-25 13:20 UTC, MinoUni commented on src/test/java/com/teamchallenge/bookti/ApplicationTests.java
Return test to check that spring context loads correctly

2024-05-25 13:20 UTC, MinoUni commented on src/test/java/com/teamchallenge/bookti/review/ReviewControllerTest.java
> +}
add whitespace

2024-05-25 13:20 UTC, MinoUni commented on src/test/java/com/teamchallenge/bookti/review/UserReviewRepositoryTest.java
> +}
add whitespace

2024-05-25 13:20 UTC, MinoUni commented on src/test/java/com/teamchallenge/bookti/review/UserReviewServiceImpTest.java
> +}
add whitespace

2024-05-29 19:51 UTC, Lyubomy-r commented on pom.xml
> +<!--        </dependency>-->
Виправив

2024-05-29 19:51 UTC, Lyubomy-r commented on pom.xml
> +            <scope>runtime</scope>
Виправив

2024-05-29 19:51 UTC, Lyubomy-r commented on src/main/java/com/teamchallenge/bookti/review/ReviewController.java
> +    }
Виправив

2024-05-29 19:52 UTC, Lyubomy-r commented on src/main/java/com/teamchallenge/bookti/review/ReviewController.java
> +    @PostMapping("/user")
Виправив

2024-05-29 19:52 UTC, Lyubomy-r commented on src/main/java/com/teamchallenge/bookti/review/ReviewController.java
> +    @DeleteMapping("/user/{reviewId}")
Виправив

2024-05-29 19:52 UTC, Lyubomy-r commented on src/main/java/com/teamchallenge/bookti/review/UserReviewServiceImp.java
> +                        () -> new UserNotFoundException(format("Reviewer's User with id <{0}> not found.", reviewId)));
Виправив

2024-05-29 19:52 UTC, Lyubomy-r commented on src/test/java/com/teamchallenge/bookti/ApplicationTests.java
Виправив

2024-05-29 19:53 UTC, Lyubomy-r commented on src/test/java/com/teamchallenge/bookti/review/ReviewControllerTest.java
> +}
Виправив

2024-05-29 19:53 UTC, Lyubomy-r commented on src/test/java/com/teamchallenge/bookti/review/UserReviewRepositoryTest.java
> +}
Виправив

2024-05-29 19:53 UTC, Lyubomy-r commented on src/test/java/com/teamchallenge/bookti/review/UserReviewServiceImpTest.java
> +}
Виправив

2024-05-31 08:34 UTC, MinoUni approved these changes

2024-05-31 11:55 UTC, merged